theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"
locale: ja
title: 社会シミュレーション研究室
title_separator: "|"
description: "芝浦工業大学 システム理工学部 電子情報システム学科 後藤裕介研究室のウェブサイトです．"
url: "https://yskgt-sim.github.io/" 