<<<<<<< HEAD
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"
locale: ja
=======
theme: jekyll-theme-minimal
>>>>>>> 6fdf5ef53c33af17eb75270aa0e62d0a2ad4e66b
title: 社会シミュレーション研究室
title_separator: "|"
description: "芝浦工業大学 システム理工学部 電子情報システム学科 後藤裕介研究室のウェブサイトです．"
url: "https://yskgt-sim.github.io/" 